dist: bionic
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - python --version

# command to install dependencies
install:
  - pip install -r requirements-test.txt
# command to run tests
script:
  - python -m unittest discover tests -v